### ISSUE TITLE
Support encoding ArrayBuffer as plain bytes

### ISSUE THREAD

**Issue by dbrgn** [kawanet/msgpack-lite#38]
Right now, typed arrays and array buffers (e.g. `Uint8Array`) will be encoded using extension types (e.g. 0x11).

```
> msgpack.encode(new Uint8Array([0x01, 0x02, 0x03]))
< [199, 3, 18, 1, 2, 3]
```

I'm working with a lot of typed arrays in my application. If I want to send plain arrays to the server, I need to convert those to an `Array`:

```
> msgpack.encode(Array.from(new Uint8Array([0x01, 0x02, 0x03])))
< [147, 1, 2, 3]
```

Sending binary data directly doesn't even seem to be possible in a browser environment without the `Buffer` library.

I'm pretty sure that this results in a new allocation and a copy of the typed array to the untyped array. In a performance critical application, that might be quite expensive... (Note: I'm only guessing here about the allocation and don't know how to verify the claim...)

If that assumption is true, might it be possible to introduce an encoding mode where an `ArrayBuffer` is serialized to the msgpack binary format directly? Or is it possible to solve that problem using a codec?

If that were possible, then efficient serialization would be possible:

```
> let array = new Uint8Array([0x01, 0x02, 0x03]);
> msgpack.encode(array.buffer, simplify=True)
< [196, 3, 1, 2, 3]
```

**Comment by kawanet** [comment]
> If that assumption is true, might it be possible to introduce an encoding mode where an ArrayBuffer is serialized to the msgpack binary format directly? Or is it possible to solve that problem using a codec?

It sounds useful.

**Comment by dbrgn** [comment]
> It sounds useful.

Great. Introducing the `Buffer` library into a browser based environment is really unnecessary now that we have `ArrayBuffer` and `TypedArray` :)

What API do you have in mind? Ideally the `bin` type would convert from/to `ArrayBuffer` directly, but that would probably break compatibility with the current extension based approach.

**Comment by dbrgn** [comment]
I assumed using codec options would be the best way.

Simple test:

```javascript
#!/usr/bin/env mocha -R spec

/*jshint -W053 */

var assert = require("assert");
var msgpackJS = "../index";
var isBrowser = ("undefined" !== typeof window);
var msgpack = isBrowser && window.msgpack || require(msgpackJS);
var TITLE = __filename.replace(/^.*\//, "");

function toArray(array) {
  return Array.prototype.slice.call(array);
}

describe(TITLE, function() {
  it("nativeArrayBuffer (encode)", function() {
    var buf = new Uint8Array([1, 2, 3]).buffer;
    var codec = msgpack.createCodec({nativeArrayBuffer: true});

    // Regular behavior
    assert.deepEqual(toArray(msgpack.encode(buf)), [0xc7, 0x03, 0x1a, 0x01, 0x02, 0x03]);

    // Buffer behavior
    assert.deepEqual(toArray(msgpack.encode(new Buffer(buf))), [0xc4, 0x03, 0x01, 0x02, 0x03]);

    // With nativeArrayBuffer option, an ArrayBuffer should behave like a Buffer
    assert.deepEqual(toArray(msgpack.encode(buf, {codec: codec})), [0xc4, 0x03, 0x01, 0x02, 0x03]);
  });
});
```

With those changes, the proper encoding function is called:

```javascript
diff --git a/lib/ext-packer.js b/lib/ext-packer.js
index 05f0cf9..1c2ebc3 100644
--- a/lib/ext-packer.js
+++ b/lib/ext-packer.js
@@ -7,6 +7,8 @@ var _encode;
 var ERROR_COLUMNS = {name: 1, message: 1, stack: 1, columnNumber: 1, fileName: 1, lineNumber: 1};
 
 function setExtPackers(codec) {
+  var nativeArrayBuffer = codec.options && codec.options.nativeArrayBuffer;
+
   codec.addExtPacker(0x0E, Error, [packError, encode]);
   codec.addExtPacker(0x01, EvalError, [packError, encode]);
   codec.addExtPacker(0x02, RangeError, [packError, encode]);
@@ -40,7 +42,9 @@ function setExtPackers(codec) {
       codec.addExtPacker(0x19, Uint8ClampedArray, packBuffer);
     }
 
-    codec.addExtPacker(0x1A, ArrayBuffer, packArrayBuffer);
+    if (!nativeArrayBuffer) {
+        codec.addExtPacker(0x1A, ArrayBuffer, packArrayBuffer);
+    }
     codec.addExtPacker(0x1D, DataView, packTypedArray);
   }
 }
diff --git a/lib/write-type.js b/lib/write-type.js
index c6bb59f..3f2f100 100644
--- a/lib/write-type.js
+++ b/lib/write-type.js
@@ -24,6 +24,7 @@ exports.getWriteType = getWriteType;
 function getWriteType(options) {
   var token = WriteToken.getWriteToken(options);
   var useraw = options && options.useraw;
+  var nativeArrayBuffer = options && options.nativeArrayBuffer;
 
   var writeType = {
     "boolean": bool,
@@ -143,8 +144,9 @@ function getWriteType(options) {
     // null
     if (value === null) return nil(encoder, value);
 
-    // Buffer
+    // Buffer & ArrayBuffer
     if (Buffer.isBuffer(value)) return bin(encoder, value);
+    if (nativeArrayBuffer && value instanceof ArrayBuffer) return bin(encoder, value);
 
     // Array
     if (IS_ARRAY(value)) return array(encoder, value);
@@ -163,8 +165,9 @@ function getWriteType(options) {
   }
 
   function object_raw(encoder, value) {
-    // Buffer
+    // Buffer & ArrayBuffer
     if (Buffer.isBuffer(value)) return raw(encoder, value);
+    if (nativeArrayBuffer && value instanceof ArrayBuffer) return raw(encoder, value);
 
     // others
     object(encoder, value);
```

But then I get the following error message:

```
  1) 16.nativearraybuffer.js nativeArrayBuffer (encode):
     TypeError: "list" argument must be an Array of Buffers
      at Function.Buffer.concat (buffer.js:359:13)
      at EncodeBuffer.pull (lib/flex-buffer.js:100:45)
      at EncodeBuffer.read (lib/flex-buffer.js:168:15)
      at Object.encode (lib/encode.js:10:18)
      at Context.<anonymous> (test/16.nativearraybuffer.js:37:38)
```

**Comment by kawanet** [comment]
@dbrgn: I've pushed 	024aa45  and 		f97b373 on [binarraybuffer](https://github.com/kawanet/msgpack-lite/tree/binarraybuffer) branch. 
Could you please confirm this works on your purpose? The branch is not shipped to npm yet.

```js
var codec = msgpack.createCodec({binarraybuffer: true, preset: true});
```

See also [test/16.binarraybuffer.js](https://github.com/kawanet/msgpack-lite/blob/binarraybuffer/test/16.binarraybuffer.js).
`binarraybuffer` options changes only the behavior for `bin` format, for both encoding and decoding.

**Comment by dbrgn** [comment]
Seems to work properly, thanks!
