### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by betimer** [kawanet/msgpack-lite#63]
Log as below:

RangeError: Maximum call stack size exceeded
at EncodeBuffer.reserve (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\flex-buffer.js:109:19)
at Array. (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-uint8.js:11:26)
at obj_to_map (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:234:16)
at object (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:165:5)
at encode (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-core.js:23:5)
at C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:239:7
at Array.forEach (native)
at obj_to_map (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:237:10)
at object (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:165:5)
at encode (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-core.js:23:5)
at array (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:192:7)
at object (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:153:33)
at encode (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-core.js:23:5)
at C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:239:7
at Array.forEach (native)
at obj_to_map (C:\Repo\rtcio-signaller\node_modules\msgpack-lite\lib\write-type.js:237:10)
2017-02-14T22:45:10.197Z - error: Ouch, an unhandled exception

**Comment by kawanet** [comment]
Show your input data which may have a circular structure (self reference).

```js
var a = [];
var b = {a: a};
a.push(b);
JSON.stringify(a); // => TypeError: Converting circular structure to JSON
msgpack.encode(a); // => RangeError: Maximum call stack size exceeded
```

**Comment by betimer** [comment]
that is the root cause. after I use another package to fix the circular obj, it begins to work.

happy to close this issue.

Thanks
