### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sschizas** [kawanet/msgpack-lite#74]
I got this error using msgpack-lite:

Unhandled rejection RangeError: Maximum call stack size exceeded
    at obj_to_map (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:234:16)
    at object (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:165:5)
    at encode (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-core.js:23:5)
    at array (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:192:7)
    at object (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:153:33)
    at encode (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-core.js:23:5)
    at /Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:239:7
    at Array.forEach (native)
    at obj_to_map (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:237:10)
    at object (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:165:5)
    at encode (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-core.js:23:5)
    at array (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:192:7)
    at object (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:153:33)
    at encode (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-core.js:23:5)
    at /Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:239:7
    at Array.forEach (native)
    at obj_to_map (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:237:10)
    at object (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:165:5)
    at encode (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-core.js:23:5)
    at array (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:192:7)
    at object (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:153:33)
    at encode (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-core.js:23:5)
    at /Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:239:7
    at Array.forEach (native)
    at obj_to_map (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:237:10)
    at object (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:165:5)
    at encode (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-core.js:23:5)
    at array (/Users/stavrosschizas/Documents/Projects/wover-backend/node_modules/msgpack-response/node_modules/msgpack-lite/lib/write-type.js:192:7)

Any thoughts?

**Comment by kawanet** [comment]
A circular structure may cause it. JSON.stringify would fire another error as below:

```
> var msgpack = require("msgpack-lite");
> var a = {};
> a.a = a
> msgpack.encode(a)
RangeError: Maximum call stack size exceeded
> JSON.stringify(a)
TypeError: Converting circular structure to JSON
```

**Comment by sschizas** [comment]
@kawanet I have checked my code and i don't see any kind of cycle reference. In order to cross validate it i used another msgpack library and i didn't get this error. I think its worth checking your code.

**Comment by JacobPatenaude-AI** [comment]
For anyone stumbling on this issue, I hit this error when I had a unpacker for an extended type but not a packer

**Comment by joyarzun** [comment]
> For anyone stumbling on this issue, I hit this error when I had a unpacker for an extended type but not a packer

Do you mean extended like an object large and deep?

I'm facing this issue as well.

Node: v12 Alpine


![image](https://user-images.githubusercontent.com/828211/87574823-eeb10d80-c69c-11ea-93f5-5ecb4fdd602f.png)

Depend on:

``` bash
➜  orders-service git:(master) npm ls msgpack-lite
sales-order-service@1.0.0 /orders-service
└─┬ fluent-logger@3.4.1
  └── msgpack-lite@0.1.26
```
